[package]
name = "RustOS"
version = "0.1.0"
authors = ["Ethan Tola <etola@d3engineering.com>"]
edition = "2018"

[dependencies]
bootloader = "0.4.0"
volatile = "0.2.3"

[package.metadata.bootimage]
default-target = "x86_64-rust_os.json"
